added ASP.NET Core hometask
onish-alex/Net.Practise pull request #17
Opened 2021-03-04 16:31 UTC by onish-alex

2021-03-05 08:57 UTC, ilya-krivolapov requested changes

2021-03-05 08:57 UTC, ilya-krivolapov commented on PhoneBook/PhoneBook/Controllers/HomeController.cs
> +            var pageLinkCount = this.configuration.GetValue<int>("ApplicationData:PageLinkCount:Default");
Это точно не стоит выносить в конфиг, так как эти параметры вполне себе могут меняться, их стоит передавать в параметрах в экшене, там же, где page.

2021-03-05 08:57 UTC, ilya-krivolapov commented on PhoneBook/PhoneBook/Controllers/HomeController.cs
> +            IConfiguration configuration)
Если хочешь получить что-то из appsettings, то следует юзать IOptions/IOptionsSnapshot/IOptionsMonitor, в зависимости от ситуации. Я немного об этом рассказывал, но можно еще вот тут почитать: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-5.0#use-ioptionssnapshot-to-read-updated-data.

2021-03-05 08:57 UTC, ilya-krivolapov commented on PhoneBook/PhoneBook/Controllers/HomeController.cs
> +            Mapper mapper,
Маппер можно зарегистрировать с помощью services.AddAutoMapper() в Startup, и тогда можешь сюда инжектить IMapper и пользоваться им.

2021-03-05 08:57 UTC, ilya-krivolapov commented on PhoneBook/PhoneBook/Controllers/HomeController.cs
> +
Вот это вот все сверху, что касается пейджинга, лучше вынести в отдельную модельку по типу PagingListViewModel, подобавлять туда свойства. где все вычисляется, а уже твою вью модельку унаследовать от нее.

2021-03-05 08:57 UTC, ilya-krivolapov commented on PhoneBook/PhoneBook/Controllers/HomeController.cs
> +            PhoneBookDbContext dbContext,
У нас хоть в этом проекте и упрощенная архитектура, лучше все же сделать какой-нибудь сервис, и уже там юзать контекст.

2021-03-05 08:57 UTC, ilya-krivolapov commented on PhoneBook/PhoneBook/Settings/MapperConfiguration.cs
> +        });
Будет красивее использовать https://docs.automapper.org/en/stable/Configuration.html#profile-instances.

2021-03-05 09:02 UTC, ilya-krivolapov requested changes

2021-03-05 09:02 UTC, ilya-krivolapov commented on PhoneBook/PhoneBook/Controllers/HomeController.cs
> +    public class HomeController : Controller
Нужно повыносить все, что связано с номерами в отдельный контроллер, там уже подумаешь как его назвать, и соответственно вьюшки тоже. А этот думаю вообще можно удалить.

2021-03-05 09:03 UTC, ilya-krivolapov commented on PhoneBook/PhoneBook/Controllers/HomeController.cs
> +    public class HomeController : Controller
Ну либо просто переименовать этот, да.

2021-03-05 09:11 UTC, ilya-krivolapov commented on PhoneBook/PhoneBook/Controllers/HomeController.cs
> +            }
За это вообще отвечает атрибут Authorize, но подробнее наверное покажу уже на ближайшей практике.

2021-03-05 09:48 UTC, ilya-krivolapov commented on PhoneBook/PhoneBook/Controllers/HomeController.cs
> +                phone.LastUpdateDate = phoneViewModel.LastUpdateDate;
Здесь можно воспользоваться автомаппером, а потом сделать dbContext.Attach к полученной сущности, затем у нее засетить State = EntityState.Modified, и наконец вызвать SaveChanges.

2021-03-05 12:53 UTC, ilya-krivolapov commented on PhoneBook/PhoneBook/Controllers/HomeController.cs
> +                phone.LastUpdateDate = phoneViewModel.LastUpdateDate;
Хотя нет, в этом случае из-за полей с датами такой способ не подойдет, они перетрутся.

2021-03-06 12:59 UTC, onish-alex commented on PhoneBook/PhoneBook/Controllers/HomeController.cs
> +            IConfiguration configuration)
Сделал эти параметры (https://github.com/onish-alex/Net.Practise/pull/17#discussion_r588101202) аргументом экшена, так что в конфигах больше смысла нет, но в основном проекте это уже пригодилось, спасибо)

2021-03-06 18:04 UTC, ilya-krivolapov commented on PhoneBook/PhoneBook/Controllers/PhoneStorageController.cs
> +        [Authorize]
У тебя сейчас нельзя переходить незалогиненным на список номеров, но к просмотру инфы по номеру, редактированию и т.д доступ все еще есть, навесь это на контроллер.

2021-03-06 18:04 UTC, ilya-krivolapov commented on PhoneBook/PhoneBook/Views/PhoneStorage/Create.cshtml
> +        }
Вот эту всю красоту можно заменить использованием тэг-хелпера asp-items:
https://stackoverflow.com/a/34624217

2021-03-06 18:04 UTC, ilya-krivolapov commented on PhoneBook/PhoneBook/ViewModels/BasePhoneViewModel.cs
> +        public Guid Id { get; set; }
На создании Id вряд ли нужен, а вот на Edit - да, соответственно имеет смысл его вынести аж туда.

2021-03-06 18:04 UTC, ilya-krivolapov commented on PhoneBook/PhoneBook/ViewModels/ConcretePhoneViewModel.cs
> +        public DateTime LastUpdateDate { get; set; }
Вот это думаю вообще можно убрать из вью модельки, а сетить уже в доменной модели, можно уже даже в сервисе.

2021-03-06 18:04 UTC, ilya-krivolapov commented on PhoneBook/PhoneBook/Services/IPhoneService.cs
> +        Task DeletePhoneAsync(Guid phoneId, Guid userId);
Общее замечание - работа с вью модельками у нас происходит только в контроллерах и вьюшках, из сервиса можно в нашем случае возвращать доменные модельки.

2021-03-06 18:04 UTC, ilya-krivolapov commented on PhoneBook/PhoneBook/Controllers/PhoneStorageController.cs
> +            var userGuid = Guid.Parse(userId);
Это можно было бы вынести в SignInManager.

2021-03-06 18:04 UTC, ilya-krivolapov commented on PhoneBook/PhoneBook/Controllers/PhoneStorageController.cs
> +            }
Возвращай здесь из сервиса доменную модельку, а эту ConcretePhoneViewModel можешь вообще удалить.

2021-03-06 18:04 UTC, ilya-krivolapov commented on PhoneBook/PhoneBook/Controllers/UserController.cs
> +                    return this.LocalRedirect(returnUrl ?? "/");
Создавай сам объект нового юзера прям здесь, и в LoginAsync передавай этот самый объект, тогда, когда он создастся в базе, у него в этом же объекте появится айдишник, и ты сможешь его тут использовать, и тебе не нужна будет эта LoginCheckViewModel.

2021-03-06 18:04 UTC, ilya-krivolapov commented on PhoneBook/PhoneBook/Controllers/UserController.cs
> +            await this.HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);
В идеале бы это конечно все перенести в тот же UserService, в LoginAsync, ты nelf можешь передавать сам объект юзера, из которого получать Id и Name, а пароль передавать отдельно.

2021-03-06 18:04 UTC, ilya-krivolapov commented on PhoneBook/PhoneBook/Services/IPhoneService.cs
> +        Task DeletePhoneAsync(Guid phoneId, Guid userId);
А для GetPage можешь какую-то свою отдельную модельку создать.

2021-03-06 18:04 UTC, ilya-krivolapov commented on PhoneBook/PhoneBook/ViewModels/ConcretePhoneViewModel.cs
> +    public class ConcretePhoneViewModel : BasePhoneViewModel
Скорее всего тебе эта моделька вообще не нужна, там были связанные с этим комменты.

2021-03-06 18:04 UTC, ilya-krivolapov commented on PhoneBook/PhoneBook/ViewModels/CreatePhoneViewModel.cs
> +        public IEnumerable<string> StatusNames { get; set; }
Этому скорее всего место в базовой модельке.

2021-03-06 18:04 UTC, ilya-krivolapov commented on PhoneBook/PhoneBook/Views/PhoneStorage/Create.cshtml
> +        }
Где-то уже комментировал.

2021-03-06 18:04 UTC, ilya-krivolapov commented on PhoneBook/PhoneBook/Views/PhoneStorage/Edit.cshtml
> +        }
Опять же, где-то писал про asp-items.

2021-04-12 15:29 UTC, merged